### ISSUE TITLE
vue父组件中修改子组件中的样式

### ISSUE THREAD

**Issue by smileyby** [smileyby/my-issue-and-bugs#15]
> vue父组件中设置的样式`style scope`时，父组件中的样式是不会影响子组件中的样式的，如果想在父组件中修改子组件的样式只需要在样式类后面添加`/deep/` 或者 `>>>` ，添加了这个之后，父组件中的样式就会穿透到子组件中了

```css
  .myclass /deep/ .name{ //第一种写法
    color:red;
  }
  .myclass >>> .name{   //二种写法
    color:red;
  }
```
