### ISSUE TITLE
IE兼容问题-表格边框消失

### ISSUE THREAD

**Issue by smileyby** [smileyby/my-issue-and-bugs#2]
```css
.table-box {
  margin-top: 30px;
  clear: both;
  width: 100%;
  box-sizing: border-box;
  text-align: center;
  border: 1px solid #e0e0e0;
}
table {
  border-collapse: collapse;
  border-spacing: 0;
}
th,td{
    border: 1px solid red;
}
```
```html
<table class="table-box"  cellspacing="0">
  <thead>
    <tr>
      <th>版本号</th>
      <th>版本名</th>
      <th>更新时间</th>
      <th>操作</th>
 	</tr>
  </thead>
  <tbody>
    <tr>
      <td colspan="4">暂无数据</td>
    </tr>
  </tbody>
</table>
```
> 上述代码在IE下打开，无数据的情况下，标题的边框会消失
> 解决办法：给table添加 `border-collapse: collapse;` css属性
```css
table {
  border-collapse: collapse;
]
```
