### ISSUE TITLE
小程序如何模拟实现表格布局？

### ISSUE THREAD

**Issue by smileyby** [smileyby/my-issue-and-bugs#67]
display:table?table-cell?

**Comment by smileyby** [comment]
注意：**这里需要根据列数，手动设置tr，th宽度**
```html
<view class="table">
  <view class="thead">
    <view class="tr">
      <view class="th">标题</view>
    </view>
  </view>
  <view class="tbody">
    <view class="tr">
      <view class="td">内容</view>
    </view>
  </view>
</view>
```
```css
.tr {
 display: table;
}
.th, .td {
 width: 100%;
 display: table-cell;
}
```
