### ISSUE TITLE
CSS效果练习

### ISSUE THREAD

**Issue by smileyby** [smileyby/my-issue-and-bugs#69]
存放一些CSS效果练习

**Comment by smileyby** [comment]
1. box-shadow

   ```css
   /* 
    * box-shadow：[inset内阴影],x偏移,y偏移,阴影模糊半径[最小为0],阴影扩散半径[最小为0],阴影颜色
    * moon 阴影月亮 concentric 阴影同心圆
   */
   body {
     background: black;
   }
   .moon {
     width: 200px;
     height: 200px;
     border-radius: 50%;
     box-shadow: 40px 40px 0 0 #fff;
   }
   .concentric {
     width: 200px;
     height: 200px;
     border-radius: 50%;
     box-shadow: 0 0 0 20px #000;
   }
   ```

2. text-shadow

   ```css
   /*
    * text-shadow: x偏移 y偏移 模糊半径 颜色值;
    * 可以为文字与“text-decoration”添加多个阴影
    * 文字阴影也会加在“text-decoration”上
    * text-decoration: [text-decoration-line] [text-decoration-color] [text-decoration-style];
    * text-decoration是一种简写属性，
    * text-decoration-line文本修饰的位置（如下划线underline，删除线line-through）
    * text-decoration-color文本修饰的颜色，不指定默认和文字颜色一致
    * text-decoration-style文本修饰的样式（如波浪线wavy实现solid虚线dashed）；要与 text-decoration-line 配合使用才能看到效果
   */
   .text-shadow {
     text-shadow: 1px 1px 2px red, -1px -1px 2px blue;
   }
   .text-decoration {
     text-decoration: line-through wavy red;   
   }
   ```

3. background

   ```css
   /*
    * background: 简写属性，可以一次声明中定义一个或多个属性
    * background: 属性被指定多个背景层时，使用逗号隔开没个背景层
    * 每一层的语法：
    * 1. 在每一层中，[attachment] [bg-image] [position] [bg-size] [repeat-style] 可以出现0-1次
    * 2. [bg-size] 只能紧接着 [position] 出现，以“/”分割，如："center/80%"
    * 3. [bg-color] 只能被包含在最后一层（因为整个元素只有一种背景颜色）
    * background-clip: 设置元素的背景（背景图、颜色）是否延伸到边框下面
    * background-color: 设置元素的背景色，属性的值为颜色值或关键字
    * background-image: 为一个元素设置一个或多个背景图像（可设置渐变）
    * background-origin: 指定背景图片属性的原点位置的背景相对区域（当使用backgroun-attachment为fixed时，该属性被忽略）
    * background-position: 为每一个背景图片设置初始位置，这个位置相对于由background-origin定义的位置图层
    * background-repeat: 定义背景图像的重复方式
    * background-size: 定义背景图像的大小
    * background-attachment: 定义背景图的位置是指在视口内固定，还是随着包含它的区块滚动
    * 以上background的属性，顺序任意
   */
   
   /* 设置文字的前景色，设置clip属性前要先设置background-image */
   .text {
     background: url('xxx.png') no-repeat;  
     background-clip: text;
     -webkit-background-clip: text;
     color: transparent;  
   }
   ```

4. clip-path + svg

   ```css
   /*
    * clip-path: 创建一个只有元素的部分区域可以显示的剪切区域（区域内显示，区域外隐藏）
    * clip-path + svg 灵活裁剪
   */
   .img {
     width: 300px;
     height: 300px;
     clip-path: url('./images/home.svg');
   }
   ```

5. border-radius

6. 3d-transform

7. transition

8. keyframe
